<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>alog-arena-oj</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>oj-modules</module>
        <module>oj-common</module>
        <module>oj-gateway</module>
        <module>oj-api</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <spring-boot.version>3.0.1</spring-boot.version>
        <spring-cloud-alibaba.version>2022.0.0.0-RC2</spring-cloud-alibaba.version>
        <spring-cloud.version>2022.0.0</spring-cloud.version>
        <mybatis-plus.version>3.5.5</mybatis-plus.version>
        <oj-api.version>1.0-SNAPSHOT</oj-api.version>
        <oj-common-core.version>1.0-SNAPSHOT</oj-common-core.version>
        <oj-common-swagger.version>1.0-SNAPSHOT</oj-common-swagger.version>
        <oj-common-redis.version>1.0-SNAPSHOT</oj-common-redis.version>
        <oj-common-security.version>1.0-SNAPSHOT</oj-common-security.version>
        <oj-common-mybatis.version>1.0-SNAPSHOT</oj-common-mybatis.version>
        <oj-common-message.version>1.0-SNAPSHOT</oj-common-message.version>
        <oj-common-elsticsearch.version>1.0-SNAPSHOT</oj-common-elsticsearch.version>
        <oj-common-file.version>1.0-SNAPSHOT</oj-common-file.version>
        <oj-common-rabbitmq.version>1.0-SNAPSHOT</oj-common-rabbitmq.version>
        <springdoc-openapi.version>2.2.0</springdoc-openapi.version>
        <fastjson2.version>2.0.43</fastjson2.version>
        <jjwt.version>0.9.1</jjwt.version>
        <jaxb-api.version>2.4.0-b180830.0359</jaxb-api.version>
        <hutool-all.version>5.8.22</hutool-all.version>
        <pagehelper.boot.version>2.0.0</pagehelper.boot.version>
        <xxl-job-core.version>2.4.0</xxl-job-core.version>
        <transmittable-thread-local.version>2.14.4</transmittable-thread-local.version>
        <aliyun-sdk-oss.version>3.17.4</aliyun-sdk-oss.version>
        <jaxb-api.version>2.3.1</jaxb-api.version>
        <activation.version>1.1.1</activation.version>
        <jaxb-runtime.version>2.3.3</jaxb-runtime.version>
        <docker-java.version>3.3.4</docker-java.version>
    </properties>

    <dependencies>
        <dependency>
            <!-- bootstrap 启动器 -->
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <!-- SpringCloud Alibaba 微服务 -->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- SpringCloud 微服务 -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- SpringBoot 依赖配置 -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>